# Generated by Django 5.2.18 on 2026-10-08 21:49

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un departamento con ese nombre.'}, max_length=120, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'db_table': 'departamentos',
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('nombre'))), 0), name='ck_departamentos_nombre_no_vacio', violation_error_message='El nombre no puede estar vacío.')],
            },
        ),
    ]
