# Generated by Django 5.2.18 on 2026-10-08 22:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_departamento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_departamentos_nombre_sin_mayusculas', violation_error_message='Ya existe un departamento con ese nombre.'),
        ),
    ]
