# Generated by Django 5.2.18 on 2026-10-09 14:54

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_nombre_sin_mayusculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='empresas.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudades',
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('nombre'))), 0), name='ck_ciudades_nombre_no_vacio', violation_error_message='El nombre no puede estar vacío.'), models.UniqueConstraint(fields=('departamento', 'nombre'), name='uq_ciudades_nombre_departamento', violation_error_message='Ya existe una ciudad con ese nombre en ese departamento.'), models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('departamento'), name='uq_ciudades_nombre_departamento_sin_mayusculas', violation_error_message='Ya existe una ciudad con ese nombre en ese departamento.')],
            },
        ),
    ]
