# Generated by Django 5.2.18 on 2026-10-09 16:29

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class CrearCategoriaSiNoExiste(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        tablas = schema_editor.connection.introspection.table_names()
        if "categorias" not in tablas:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
            return
        # La tabla vino de bd_inicial.sql. Se alinea con el modelo sin recrearla,
        # porque empresas_categorias ya la referencia.
        schema_editor.execute(
            "UPDATE categorias SET descripcion = '' WHERE descripcion IS NULL"
        )
        schema_editor.execute(
            "ALTER TABLE categorias ALTER COLUMN descripcion SET NOT NULL"
        )
        schema_editor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_categorias_nombre_sin_mayusculas "
            "ON categorias ((LOWER(nombre)))"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS categorias_nombre_0c0c1ae2_like "
            "ON categorias (nombre varchar_pattern_ops)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_ciudad"),
    ]

    operations = [
        CrearCategoriaSiNoExiste(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        error_messages={
                            "unique": "Ya existe una categoría con ese nombre."
                        },
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "db_table": "categorias",
                "ordering": ["nombre"],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                django.db.models.functions.text.Trim(models.F("nombre"))
                            ),
                            0,
                        ),
                        name="ck_categorias_nombre_no_vacio",
                        violation_error_message="El nombre no puede estar vacío.",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nombre"),
                        name="uq_categorias_nombre_sin_mayusculas",
                        violation_error_message="Ya existe una categoría con ese nombre.",
                    ),
                ],
            },
        ),
    ]
