# Generated by Django 5.2.18 on 2026-10-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción'),
        ),
    ]
