# Generated by Django 5.2.18 on 2026-10-09 17:07

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_descripcion_limite_caracteres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('ruc', models.CharField(error_messages={'unique': 'Ya existe una empresa con ese RUC.'}, max_length=20, unique=True, verbose_name='RUC')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('es_cliente', models.BooleanField(default=False, verbose_name='Es cliente')),
                ('es_proveedor', models.BooleanField(default=False, verbose_name='Es proveedor')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='empresas', to='empresas.categoria', verbose_name='Categorías')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresas',
                'ordering': ['razon_social', 'pk'],
                'indexes': [models.Index(fields=['razon_social'], name='idx_empresas_razon_social'), models.Index(fields=['email'], name='idx_empresas_email'), models.Index(fields=['es_cliente'], name='idx_empresas_es_cliente'), models.Index(fields=['es_proveedor'], name='idx_empresas_es_proveedor'), models.Index(fields=['activo'], name='idx_empresas_activo')],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('razon_social'))), 0), name='ck_empresas_razon_social_no_vacia', violation_error_message='La razón social no puede estar vacía.'), models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('ruc'))), 0), name='ck_empresas_ruc_no_vacio', violation_error_message='El RUC no puede estar vacío.'), models.CheckConstraint(condition=models.Q(('es_cliente', True), ('es_proveedor', True), _connector='OR'), name='ck_empresas_cliente_o_proveedor', violation_error_message='La empresa debe ser cliente, proveedor o ambas.')],
            },
        ),
    ]
