# Generated by Django 5.2.18 on 2026-10-10 14:46

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('cargo', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'contactos',
                'ordering': ['apellido', 'nombre', 'pk'],
                'indexes': [models.Index(fields=['empresa'], name='idx_contactos_empresa')],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('nombre'))), 0), name='ck_contactos_nombre_no_vacio', violation_error_message='El nombre no puede estar vacío.'), models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('apellido'))), 0), name='ck_contactos_apellido_no_vacio', violation_error_message='El apellido no puede estar vacío.')],
            },
        ),
    ]
