# Generated by Django 5.2.18 on 2026-10-10 15:28

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_contacto'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('email'))), 0), django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('telefono'))), 0), _connector='OR'), name='ck_contactos_email_o_telefono', violation_error_message='Indicá un email o un teléfono.'),
        ),
    ]
