# Generated by Django 5.2.18 on 2026-10-10 16:01

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_contacto_email_o_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=20, verbose_name='Código postal')),
                ('tipo', models.CharField(max_length=40, verbose_name='Tipo')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='empresas.ciudad', verbose_name='Ciudad')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='empresas.contacto', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'db_table': 'direcciones',
                'ordering': ['direccion', 'pk'],
                'indexes': [models.Index(fields=['contacto'], name='idx_direcciones_contacto'), models.Index(fields=['ciudad'], name='idx_direcciones_ciudad')],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('direccion'))), 0), name='ck_direcciones_direccion_no_vacia', violation_error_message='La dirección no puede estar vacía.'), models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('tipo'))), 0), name='ck_direcciones_tipo_no_vacio', violation_error_message='El tipo no puede estar vacío.')],
            },
        ),
    ]
