# Generated by Django 5.2.18 on 2026-10-10 18:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_direccion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(fields=('contacto', 'ciudad', 'direccion'), name='uq_direcciones_contacto_ciudad_direccion', violation_error_message='Ya existe esa dirección para ese contacto en esa ciudad.'),
        ),
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('direccion'), models.F('contacto'), models.F('ciudad'), name='uq_direcciones_contacto_ciudad_direccion_sin_mayusculas', violation_error_message='Ya existe esa dirección para ese contacto en esa ciudad.'),
        ),
    ]
